# -*- coding: utf-8 -*-
"""Hpc-06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TY6ZBTFZg0x617yq1lZ5Ni3Ozy1s8y6B

**ASSIGNMENT – 1**

**Identification of NUMA Architecture and System Topology**

To identify and understand NUMA architecture,CPU-core mapping, and memory node distribution in a Linux-based system.
"""

!lscpu | grep NUMA

!apt -get update
!apt-get install -y numactl

"""**ASSIGNMENT – 2**

**Memory Bandwidth Measurement on Single NUMA Node**

To measure effective memory bandwidth using large
array operations
"""

!numactl --hardware

!lscpu

"""**ASSIGNMENT – 3**

**Local vs Remote Memory Access Performance (NUMA- Aware Execution)**

To compare performance between local and remote memory access in a NUMA-enabled system.
"""

import numpy as np
import time
N=100_000_000
a=np.ones(N,dtype=np.float64)
b=np.ones(N,dtype=np.float64)
start=time.time()
c=a+b
end=time.time()
execution_time=end-start
bytes_accesses=3*a.nbytes
bandwidth=bytes_accesses/execution_time/1e9
print("Execution Time:",execution_time,"seconds")
print("Memory Bandwidth:",bandwidth,"GB/s")

!numactl --cpunodebind=0  --membind=0 python3 benchmark.py

"""**ASSIGNMENT – 4**

**Impact of Multi-threaded Memory Access on NUMA Systems**

To study how multi-threaded memory access behaves on NUMA systems and the impact of memory locality.
"""

import numpy as np
import threading
import time

N = 50_000_000
a = np.ones(N)

def worker():
    global a
    a = a * 2

threads = []
start = time.time()

for i in range(4):
    t = threading.Thread(target=worker)
    threads.append(t)
    t.start()

for t in threads:
    t.join()

end = time.time()
print("Execution Time:", end - start, "seconds")

!numactl --cpunodebind=0  --membind=0 python3 /content/hpc_06.py

"""**ASSIGNMENT – 5**

**Comparative Study of NUMA-Unaware vs NUMA-Aware Execution **

To analyze performance differences between NUMA-unaware and NUMA-aware application execution.
"""

import numpy as np
import time

N = 50_000_000
a = np.ones(N)

start = time.time()
for i in range(5):
    a = a * 2
end = time.time()

print("Execution Time:", end - start, "seconds")

!numactl --hardware

!numactl --cpunodebind=0 --membind=0 python3 /content/hpc_06.py